In [12]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

data=load_digits()
X=pd.DataFrame(data.data)
y=pd.DataFrame(data.target)
X.head()
X_train,X_test,y_train,y_test = train_test_split(X,y,shuffle=False, test_size=0.25)
np.shape(X_train), np.shape(y_train),np.shape(X_test), np.shape(y_test)

((1347, 64), (1347, 1), (450, 64), (450, 1))

In [22]:
np.linalg.norm(X_train.values-X_test.values, axis=0)

ValueError: operands could not be broadcast together with shapes (1347,64) (450,64)

In [24]:
import scipy

In [62]:
temp=scipy.spatial.distance.cdist(X_train, X_test, metric='euclidean')
np.shape(temp)
euc_norm=pd.DataFrame(temp)#строка - расстояние между первым трейном и всеми тестами. Столбец - расстояние между тестом и всеми трейнами
euc_norm.head(10)

,0,1,2,3,4,5,6,7,8,9,...,440,441,442,443,444,445,446,447,448,449
0,41.121770,53.702886,47.000000,43.977267,46.914816,47.655010,49.729267,50.239427,43.312816,40.546270,...,39.874804,49.749372,52.640289,51.458721,49.989999,36.249138,26.627054,50.378567,37.067506,47.031904
1,52.990565,46.400431,57.236352,59.118525,48.249352,44.788391,45.343136,45.727453,51.797683,50.685304,...,52.009614,48.969378,42.965102,32.572995,47.707442,51.390661,59.177699,38.587563,48.569538,50.328918
2,53.619026,53.740115,52.144031,53.291650,47.801674,46.829478,47.759816,45.869380,50.477718,46.711883,...,59.076222,47.927028,46.335731,39.191836,46.936127,51.826634,52.009614,38.340579,50.774009,43.954522
3,33.645208,52.239832,39.064050,36.290495,50.318983,42.402830,43.726422,41.146081,57.227616,36.810325,...,37.934153,55.569776,50.099900,43.988635,58.566202,40.286474,55.551778,49.527770,44.147480,41.267421
4,57.697487,59.849812,64.907627,65.406422,23.430749,43.393548,43.692105,44.766059,30.951575,52.952809,...,48.620983,26.172505,55.794265,48.723711,31.416556,53.981478,51.449004,46.882833,52.668776,50.970580
5,31.511903,54.626001,42.790186,38.626416,53.619026,44.056782,44.192760,47.159304,58.940648,39.012818,...,35.355339,55.380502,48.487112,42.708313,57.870545,29.325757,49.325450,46.904158,32.557641,38.496753
6,57.227616,60.365553,60.058305,60.448325,33.955854,28.053520,31.064449,28.000000,38.314488,51.807335,...,44.022721,39.661064,45.639895,43.243497,39.585351,52.191953,45.354162,33.466401,48.207883,40.224371
7,54.304696,33.226495,55.253959,56.356011,61.814238,59.304300,60.108236,60.216277,58.446557,52.076866,...,57.775427,60.917978,49.769469,45.978256,58.608873,55.605755,60.456596,54.516053,55.928526,56.267220
8,44.204072,49.949975,48.846699,44.643029,54.295488,41.303753,43.358967,41.677332,55.072679,42.201896,...,47.169906,52.172790,41.133928,38.431758,51.361464,40.037482,48.041649,34.885527,37.000000,28.337255
9,41.569219,51.449004,47.539457,44.732538,58.086143,44.899889,44.609416,47.906158,58.608873,47.233463,...,38.871583,54.954527,51.923020,48.383882,52.134442,36.262929,47.265209,49.929951,28.827071,40.926764

In [66]:
y_pred=y_train.iloc[euc_norm.idxmin(axis=0) ]
y_pred.head()

      0
705   3
894   7
708   3
1089  3
1291  4

In [68]:
from sklearn.metrics import accuracy_score
sc=accuracy_score(y_test,y_pred)

In [70]:
file=open('subc2w531.txt','w+')
file.write(str(1-sc))
file.close()

In [71]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=1000, random_state=1)

In [72]:
clf.fit(X_train,y_train)

D:\Program Files\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [75]:
y_pred2=clf.predict(X_test)

In [76]:
sc2=accuracy_score(y_test,y_pred2)
sc2

0.9333333333333333

In [78]:
file=open('subc2w532.txt','w+')
file.write(str(1-sc2))
file.close()